export const createInspection = ({
  carrier = "5d3633fda9663d0011279333",
  custom_fields = {} as any,
  conversation = {} as any,
  policy_id = "5f9c62efa0db1340193777d7",
  policy_type = "new",
  first_name = "Test",
  last_name = "User",
  email = "support@flyreel.co",
  invalid_email = false,
  phone = "+13035551212",
  code = "1234567890",
  status = "pending",
  expiration = "2030-01-01 18:00:00.000Z",
  carrier_expiration = "2030-01-03 18:00:00.000Z",
  address1 = "3000 Lawrence St",
  address2 = undefined as string | undefined,
  city = "Denver",
  state = "CO",
  zip_code = "80205",
  country = "US" as "US" | "CA",
  location: {
    type = "Point" as const,
    coordinates = [39.761514, -104.979007],
  } = {},
  ordered_location: {
    type: ol_type = "Point" as const,
    coordinates: ol_coordinates = [39.761514, -104.979007],
  } = {},
  timezone: {
    dst_offset = 3600,
    raw_offset = -25200,
    timezone_id = "America/Denver",
    timezone_name = "Mountain Daylight Time",
  } = {},
  detected_address = "3000 Lawrence St, Denver, CO 80205",
  estated = undefined as any,
  agent_name = `Test Agent`,
  agent_email = "test.agent@flyreel.co",
  agent_phone = "+13035551212",
  reviewer = undefined as string | undefined,
  review_started = "2020-10-01:00:00.000+00:00",
  review_completed = "2020-10-01T00:00:00.000+00:00",
  flyreel_completed = false,
  flyreel_type = "inspection",
  contact_log = [] as any,
  last_contacted = "2020-10-01T00:00:00.000+00:00",
  meta: {
    external_id = "00107f7e-921f-41ce-98ee-d027ce6c9f8d" as string | undefined,
    forms: {
      self_inspection_form_id = undefined as string | undefined,
      self_inspection_internal_form = undefined as string | undefined,
    } = {},
    inspection_form_id = undefined as string | undefined,
    billing = undefined as any,
  } = {},
} = {}): any => {
  const inspection = {
    carrier,
    custom_fields,
    conversation,
    policy_id,
    policy_type,
    first_name,
    last_name,
    email,
    invalid_email,
    phone,
    code,
    status,
    expiration,
    carrier_expiration,
    address1,
    address2,
    city,
    state,
    zip_code,
    country,
    location: {
      type,
      coordinates,
    },
    ordered_location: {
      type: ol_type,
      coordinates: ol_coordinates,
    },
    timezone: {
      dst_offset,
      raw_offset,
      timezone_id,
      timezone_name,
    },
    detected_address,
    estated,
    agent_name,
    agent_email,
    agent_phone,
    reviewer,
    review_started,
    review_completed,
    flyreel_completed,
    flyreel_type,
    contact_log,
    last_contacted,
    meta: {
      external_id,
      forms: {
        self_inspection_form_id,
        self_inspection_internal_form,
      },
      inspection_form_id,
      billing,
    },
  };

  return {
    ...inspection,
    expiration: new Date(inspection.expiration),
    carrier_expiration: new Date(inspection.carrier_expiration),
    review_started: new Date(review_started),
    review_completed: new Date(review_completed),
  };
};
