steps:
  - name: "gcr.io/cloud-builders/npm"
    id: "Install node_modules based on package.json"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    id: "Install Serverless framework using npm"
    args: ["install", "-g", "serverless"]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access --secret=serverless-key latest > /workspace/serverless-key.json
  - name: "gcr.io/cloud-builders/npm"
    id: "Deploy Serverless framework"
    entrypoint: bash
    args: ["-c", "npx serverless deploy -v"]

options:
  env:
    - 'SLS_STAGE=dev'
    - 'PROJECT=flyreel-infrastructure-dev'
