steps:
  - name: "gcr.io/cloud-builders/npm"
    id: "Install node_modules based on package.json"
    args: ["install"]
  # NOTE: npx is used as workaround to allow serverless command to be found
  # https://github.com/serverless/serverless/issues/4889
  # - name: 'gcr.io/cloud-builders/npm'
  #   id: 'Install npx'
  #   args: ['install', '-g', 'npx']
  - name: "gcr.io/cloud-builders/npm"
    id: "Install Serverless framework using npm"
    args: ["install", "-g", "serverless"]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access --secret=serverless-key latest > /workspace/serverless-key.json
    # args:
    #   - kms
    #   - decrypt
    #   - --ciphertext-file=serverless-key.json.enc
    #   - --plaintext-file=serverless-key.json
    #   - --location=global
    #   - --keyring=${_KEYRING}
    #   - --key=${_KEY}
  - name: "gcr.io/cloud-builders/npm"
    id: "Deploy Serverless framework"
    entrypoint: bash
    args: ["-c", "npx serverless deploy -v"]
    # args: ['run serverless:deploy']
substitutions:
  _KEYRING: serverless-key-ring
  _KEY: serverless-key
