service: corelogic-integration

package:
  exclude:
    - node_modules/**

provider:
  name: google
  runtime: nodejs14
  stage: ${env:SLS_STAGE}
  region: ${env:GCP_REGION}
  project: ${env:GCP_PROJECT}
  credentials: /workspace/serverless-key.json

plugins:
  - serverless-plugin-typescript
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin

functions:
  notify_cancellation:
    handler: notifyCancellation
    events:
      - http: http
  notify_extension:
    handler: notifyExtension
    events:
      - http: http
  export_inspection:
    handler: exportInspection
    timeout: 600s
    events:
      - http: http
