
service: serverless-functions

package:
  exclude:
    - node_modules/**

provider:
  name: google
  runtime: nodejs12
  stage: dev
  region: us-central1
  project: flyreel-infrastructure-dev
  # the path to the credentials file needs to be absolute
  # credentials: keyfile.json
  credentials: ~/documents/serverless-key.json
  # credentials: /workspace/serverless-key.json

plugins:
  - serverless-plugin-typescript
  - serverless-google-cloudfunctions
  # - serverless-dotenv-plugin

functions:
  notify_cancellation:
    handler: notifyCancellation
    events:
      - http: http
  notify_extension:
    handler: notifyExtension
    events:
      - http: http