
service: serverless-functions

package:
  exclude:
    - node_modules/**

provider:
  name: google
  runtime: nodejs12
  stage: ${env:SLS_STAGE}
  region: us-central1
  project: ${env:PROJECT}
  credentials: /workspace/serverless-key.json

plugins:
  - serverless-plugin-typescript
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin

functions:
  notify_cancellation:
    name: notifyCancellation
    handler: notifyCancellation
    events:
      - http: http
  notify_extension:
    name: notifyExtension
    handler: notifyExtension
    events:
      - http: http