
service: corelogic-integration

package:
  exclude:
    - node_modules/**

provider:
  name: google
  runtime: nodejs12
  stage: ${env:SLS_STAGE}
  region: us-central1
  project: ${env:GCP_PROJECT}
  credentials: /workspace/serverless-key.json

plugins:
  - serverless-plugin-typescript
  - serverless-google-cloudfunctions

functions:
  notify_cancellation:
    handler: notifyCancellation
    events:
      - http: http
  notify_extension:
    handler: notifyExtension
    events:
      - http: http